on: [ push, pull_request ]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy
        run: |
          cargo clippy --all-features
      - name: Run tests
        run: |
          cargo test --all-features